ALTER TABLE public.person ADD CONSTRAINT PK_person PRIMARY KEY (person_id);
ALTER TABLE public.enterprise ADD CONSTRAINT PK_enterprise PRIMARY KEY (enterprise_id);
ALTER TABLE public.practice ADD CONSTRAINT PK_practice PRIMARY KEY (practice_id);
ALTER TABLE public.practice ADD CONSTRAINT FK_practice_enterprise FOREIGN KEY (enterprise_id) REFERENCES public.enterprise(enterprise_id);
ALTER TABLE public.patient ADD CONSTRAINT PK_patient PRIMARY KEY (patient_id);
ALTER TABLE public.patient ADD CONSTRAINT FK_patient_practice FOREIGN KEY (practice_id) REFERENCES public.practice(practice_id);
ALTER TABLE public.patient ADD CONSTRAINT FK_patient_person FOREIGN KEY (person_id) REFERENCES public.person(person_id);
ALTER TABLE public.config_group ADD CONSTRAINT PK_config_group PRIMARY KEY (config_group_id);
ALTER TABLE public.config ADD CONSTRAINT PK_config PRIMARY KEY (config_id);
ALTER TABLE public.config ADD CONSTRAINT FK_config_group FOREIGN KEY (group_id) REFERENCES public.config_group(config_group_id);
ALTER TABLE public.codesystem ADD CONSTRAINT PK_codesystem PRIMARY KEY (code);
ALTER TABLE public.uom ADD CONSTRAINT PK_uom PRIMARY KEY (code);
ALTER TABLE public.obstype ADD CONSTRAINT PK_obstype PRIMARY KEY (obstype_id);
ALTER TABLE public.obscategory ADD CONSTRAINT PK_obscategory PRIMARY KEY (obscategory_id);
ALTER TABLE public.obsterm ADD CONSTRAINT PK_obsterm PRIMARY KEY (obsterm_id);
ALTER TABLE public.obsterm ADD CONSTRAINT FK_obsterm_obstype FOREIGN KEY (obstype_id) REFERENCES public.obstype(obstype_id);
ALTER TABLE public.obsterm ADD CONSTRAINT FK_obsterm_obscategory FOREIGN KEY (obscategory_id) REFERENCES public.obscategory(obscategory_id);
ALTER TABLE public.obsterm_codesystem ADD CONSTRAINT PK_obsterm_codesystem PRIMARY KEY (obsterm_id);
ALTER TABLE public.obsterm_codesystem ADD CONSTRAINT FK_obsterm_cs FOREIGN KEY (codesystem_code) REFERENCES public.codesystem(code);
ALTER TABLE public.obsterm_codesystem ADD CONSTRAINT FK_cs_obsterm FOREIGN KEY (obsterm_id) REFERENCES public.obsterm(obsterm_id);
ALTER TABLE public.patient_obs ADD CONSTRAINT PK_patient_obs PRIMARY KEY (patient_obs_id);
ALTER TABLE public.patient_obs ADD CONSTRAINT FK_patient_obs_uom FOREIGN KEY (uom_code) REFERENCES public.uom(code);
ALTER TABLE public.patient_obs ADD CONSTRAINT FK_patient_obs_obsterm FOREIGN KEY (obsterm_id) REFERENCES public.obsterm(obsterm_id);
ALTER TABLE public.patient_obs ADD CONSTRAINT FK_patient_obs_patient FOREIGN KEY (patient_id) REFERENCES public.patient(patient_id);
ALTER TABLE public.patient_obs_detail ADD CONSTRAINT PK_patient_obs_detail PRIMARY KEY (patient_obs_detail_id);
ALTER TABLE public.patient_obs_detail ADD CONSTRAINT FK_patient_obs_detail_obsterm FOREIGN KEY (obsterm_id) REFERENCES public.obsterm(obsterm_id);
ALTER TABLE public.patient_obs_detail ADD CONSTRAINT FK_patient_obs_detail_patient_obs FOREIGN KEY (patient_obs_id) REFERENCES public.patient_obs(patient_obs_id);
ALTER TABLE public.patient_obs_detail ADD CONSTRAINT FK_patient_obs_obstype FOREIGN KEY (obstype_id) REFERENCES public.obstype(obstype_id);
ALTER TABLE public.obsterm_range ADD CONSTRAINT PK_obsterm_range PRIMARY KEY (obsterm_range_id);
ALTER TABLE public.obsterm_range ADD CONSTRAINT FK_obsterm_range_uom FOREIGN KEY (uom_code) REFERENCES public.uom(code);
ALTER TABLE public.obsterm_range ADD CONSTRAINT FK_obsterm_range_obsterm FOREIGN KEY (obsterm_id) REFERENCES public.obsterm(obsterm_id);
